### ISSUE TITLE
fix views

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#22]
- remove superfluous buttons (see below linked commit, where they were removed)
- fix linking of buttons (e.g. filterpopup)

was correctly linked and working at 96875c69bf13a997685f127dee00f59bf1eac727 at least
you probably copy-pasted too much in views , dunno

something else TODO:
- remove "users near you location" in settings
- the "to user" field in contactRequest should not be editable (because the toUser will be given as argument)
- on/off button should disable matchings, not location tracking

**Comment by Gogeta05** [comment]
Mockup war veraltet, daher div. Buttons falsch platziert --> ist nun geändert
Auch der Rest wurde behoben.

Für Popups gibts ein eigenes Issue, die werden als Nächstes funktionstüchtig gemacht.
