### ISSUE TITLE
make Popup views as popups

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#23]
- userPopup should be a popup that pops up when you click a user in the home view
- filterPopup should be a popup that pops up when you press the "filter" button

(look into jquery mobile popups, they should give us everything we need)

thx

**Comment by Gogeta05** [comment]
Ich geh jetzt erstmal schlafen und mach die Popups nach dem Mittagessen (ab ~ 13 Uhr).
Bin seit über 20h am Stück wach und jetzt einfach hundemüde.

Auch noch auftretende Fehler behebe ich nach dem Mittagessen.

**Comment by Gogeta05** [comment]
Erledigt, siehe 24764133c3baf39f0542af99a1ecccc59591d517
