### ISSUE TITLE
interests of user are not saved in DB with the user? 

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#24]
The user interests are not saved in database upon registration

In the register view:
The interests are correctly stored in the user before and after calling user.save()
But if i pull the user from the database the interests are suddenly null (hence i believe they are not saved)

note that this already happened in the implementation of session management (7da1acca8c27fe2289a7394ff1fa5cc70f5ee4e5) which is why you needed to do efdedb0cbf8cb58c7d94f6306951980b54e59e93
but it should never happen that interests are null in the first place.
(now no interests are displayed as a result)

We should fix this asap, since this may mean that the message box isn't saved either (haven't tried)
very grevious :/

**Comment by YtGz** [comment]
updated annotations.
see: http://www.avaje.org/cascade.html
still not working -> maybe because of recursive entries in table Interests?

**Comment by MasterMoritz** [comment]
alright, i solved it pretty much, almost there

**Comment by YtGz** [comment]
nice ;)
