### ISSUE TITLE
MessageBox isn't saved

### ISSUE THREAD

**Issue by YtGz** [Gogeta05/Project_Poseidon#25]
Util.getSessionUser().msgBox wieder NULL in der privateMessageList()-Controllermethode, d.h. Speicherung in Datenbank für MessageBox funktioniert wieder nicht!

**Comment by MasterMoritz** [comment]
got the messageBox working, but the messages were not saved then me thinks.

try different annotations/techniques, google gives a ton of different ones.
One of them got to be working for OneToOne relation :P

**Comment by MasterMoritz** [comment]
just saw that owner is never set in MessageBox.
maybe that is the error

**Comment by MasterMoritz** [comment]
alright, 'twas the error
fix rolling out soon

**Comment by MasterMoritz** [comment]
fixed, please implement the whole system now:
- messages have to be clickable to show the message details in a view
- you probably need additional attributes in the Message class (like proposed time ,etc.)
- some other things i can't think of yet

note that admin has no messages atm.
log in with:
- email: still@virg.in
- password: sadpanda
