### ISSUE TITLE
sub interests not displayed in userPopup

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#26]
It's nice to have checkboxes but your commit b0c6168f1def44b2974add7161525b6d5c68aa58 disabled the displaying of subinterests in the userPopup

**Comment by MasterMoritz** [comment]
05f22502cf948e07fc0a712e84ea945a3af65332
- only adds 1 layer of recursion (see attachments)

Only first layer of recursion:
![clipboard01](https://cloud.githubusercontent.com/assets/10097456/5890129/f945bc82-a44c-11e4-9e56-d4573e29f4fa.jpg)

Contains everything:
![clipboard02](https://cloud.githubusercontent.com/assets/10097456/5890130/fec655e0-a44c-11e4-9bf0-dcef2e690f64.jpg)
- ebeandeferred (fixed by 8ceae2eef4cbc46b7e66841beb0c6143dc57195e)
- mysterious 2checkboxes overlayed
- we need collapsible, don't want to list 2000 interests at once

please test everything before comitting

**Comment by Gogeta05** [comment]
should be fixed with next commit (bf2286f24f5d81e29d4fc1d0435d4cf08db22a26)
![fix_issue_26](https://cloud.githubusercontent.com/assets/10181209/5890427/ce2f9564-a45a-11e4-82c0-a6dda323ca25.png)

**Comment by MasterMoritz** [comment]
still looks like my first screenshot 
(and even in your screenshot i can't see any collapsibles and the other layers of recursion [pcgames has subinterests])

**Comment by Gogeta05** [comment]
I'm working now on collapsibles to get the display even better.
Why the recursion only calls 1 times I don't know 'cause I don't implemented it.

**Comment by Gogeta05** [comment]
Now it works (used your recursion call @MasterMoritz )
