### ISSUE TITLE
enable/disable locationTracking

### ISSUE THREAD

**Issue by YtGz** [Gogeta05/Project_Poseidon#27]
if(lt_enabled) {
    document.write('<script type="text/javascript" src="'@routes.Assets.at("javascripts/locationTracker.js")'"></script>');
}

-> easier than AJAX, but has to be executed before window.onload():
         -> maybe rebuild the page after turning on/off?

**Comment by MasterMoritz** [comment]
i think we won't have to enable/disable it manually, 
the browser/smartphone asks the user anyway
(afaik the setting is saved automatically)

we don't have time for it imo

**Comment by YtGz** [comment]
agreed
