### ISSUE TITLE
choose lift for contact request

### ISSUE THREAD

**Issue by YtGz** [Gogeta05/Project_Poseidon#32]
additional view before contactRequest to choose the lift (life search)
for contactRequest view: insert postal code and chosen lift

**Comment by MasterMoritz** [comment]
note that the current postal code and lift name are now saved in the User model
you can use this directly 
(the stored liftname as first option, the lift should still be choosable for the saved postal code, a selector for this is already implemented in the Home view, maybe copy it)

**Comment by YtGz** [comment]
hmm, ok
