### ISSUE TITLE
Bug #2 [Unexpected Exception]

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#7]
this bug occurred after your commit 20c086bfa3ff56412519b6382e4d79eed2ab5682
you may want to look into this.

![clipboard02](https://cloud.githubusercontent.com/assets/10097456/5790635/7f2def64-9ea2-11e4-85d5-c9a5e83d36af.jpg)

**Comment by Gogeta05** [comment]
Wrote header/footer static into every file
