### ISSUE TITLE
Bug #1 [Compilation Error]

### ISSUE THREAD

**Issue by MasterMoritz** [Gogeta05/Project_Poseidon#8]
This bug occurred after your commit 0c658c177a911e0158a438133982a1ba42ce5320
you may want to look into this.

![clipboard01](https://cloud.githubusercontent.com/assets/10097456/5790644/f22de546-9ea2-11e4-9d75-5d7fd300b02f.jpg)

**Comment by Gogeta05** [comment]
old version of displayLIfts used
